"""Nova coluna tamanho na tabela produto

Revision ID: 2dbb58ea5c28
Revises: aec05c50ad9a
Create Date: 2021-11-19 20:00:34.951986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dbb58ea5c28'
down_revision = 'aec05c50ad9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('tamanho', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produto', 'tamanho')
    # ### end Alembic commands ###
