"""Colum Tamanho Tabela Produto

Revision ID: 3212973a76f6
Revises: 2dbb58ea5c28
Create Date: 2021-11-19 20:32:32.700627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3212973a76f6'
down_revision = '2dbb58ea5c28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
