"""back_populates

Revision ID: c76ba690a729
Revises: 8c2bfc19d1b2
Create Date: 2021-11-20 17:59:04.049439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c76ba690a729'
down_revision = '8c2bfc19d1b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
